#===============================================================================
# User Options
#===============================================================================

# Compiler can be set below, or via environment variable
CC        = nvcc
OPTIMIZE  = yes
DEBUG     = no
ARCH      = sm_60
#MPI_ROOT  = /usr/lib/x86_64-linux-gnu/openmpi
#LAUNCHER  = /usr/bin/mpirun -n 2
NVHPC_SDK = /opt/nvidia/hpc_sdk/Linux_aarch64/25.1/cuda/12.6
MPI_ROOT  = $(NVHPC_SDK)/comm_libs/12.6/openmpi4/latest
LAUNCHER  = bash -c

#===============================================================================
# Program name & source code list
#===============================================================================

mpi-program = main-mpi
nccl-program = main-nccl

mpi-source = main-mpi.cu
nccl-source = main-nccl.cu

mpi-obj = $(mpi-source:.cu=.o)
nccl-obj = $(nccl-source:.cu=.o)

#===============================================================================
# Sets Flags
#===============================================================================

# Standard Flags
CFLAGS := $(EXTRA_CFLAGS) -std=c++14 -I$(MPI_ROOT)/include           -Xcompiler -Wall -arch=$(ARCH)

# Linker Flags
LDFLAGS = -L$(MPI_ROOT)/lib -lmpi -lnccl

# Debug Flags
ifeq ($(DEBUG),yes)
  CFLAGS += -g -DDEBUG
  LDFLAGS  += -g
endif

# Optimization Flags
ifeq ($(OPTIMIZE),yes)
  CFLAGS += -O3
endif
#===============================================================================
# Targets to Build
#===============================================================================

$(mpi-program): $(mpi-obj) Makefile
	$(CC) $(CFLAGS) $(mpi-obj) -o $@ $(LDFLAGS)

$(nccl-program): $(nccl-obj) Makefile
	$(CC) $(CFLAGS) $(nccl-obj) -o $@ $(LDFLAGS)

%.o: %.cu Makefile
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	rm -rf $(mpi-program) $(mpi-obj)
	rm -rf $(nccl-program) $(nccl-obj)

include ../include/pingpong-NVIDIA

run: $(mpi-program) $(nccl-program)
	$(LAUNCHER) "$(COMMAND)"

run_mem: $(mpi-program) $(nccl-program)
	nvidia-smi --query-gpu=memory.used,memory.total --format=csv --loop-ms=1 > log.mem &
	$(LAUNCHER) "$(COMMAND)"
	pkill nvidia-smi
	../scripts/m.sh

