LAUNCHER = bash -c
#===============================================================================
# Targets to Build
#===============================================================================

build: setup.py
	python setup.py build

clean:
	rm -rf *.egg-info *.so build __pycache__

include ../include/convolutionDeformable-AMD

run: build
	$(LAUNCHER) "$(COMMAND)"

run_mem: build
	../scripts/rocm-smi.sh > log.mem &
	$(LAUNCHER) "$(COMMAND)"
	pkill rocm-smi.sh
	../scripts/rocm-m.sh

