regexps = {
  'accuracy':'(?:Average execution time of accuracy kernel: )([0-9.+-e]+)(?: \(us\))',
  'ace':'(?:Offload time: )([0-9.+-e]+)(?: \(ms\))',
  'adam':'(?:Average kernel execution time )([0-9.+-e]+)(?: \(ms\))',
  'addBiasResidualLayerNorm':'',
  'adv':'(?:elapsed time=)([0-9.+-e]+)(?: )',
  'aes':'(?:Average kernel execution time )([0-9.+-e]+)(?: \(s\))',
  'affine':'(?:Average kernel execution time )([0-9.+-e]+)(?: \(s\))',
  'aidw':'(?:Average execution time of AIDW_Kernel_Tiled )([0-9.+-e]+)(?: \(s\))',
  'aligned-types':'(?:Avg. time: )([0-9.+-e]+)(?: ms)',
  'all-pairs-distance':'(?:Average kernel execution time \(w/o? shared memory\): )([0-9.+-e]+)(?: \(us\))',
  'allreduce':'',
  'amgmk':'(?:Total Wall time = )([0-9.+-e]+)(?: seconds.)',
  'ans':'(?:Total elapsed time )([0-9.+-e]+)(?: \(s\))',
  'aobench':'(?:Average render time: )([0-9.+-e]+)(?: sec)',
  'aop':'(?:elapsed time for each run *: )([0-9.+-e]+)(?:ms)',
  'asmooth':'(?:Average filtering time )([0-9.+-e]+)(?: \(s\))',
  'assert':'(?:Kernel time : )([0-9.+-e]+)',
  'asta':'(?:Average kernel execution time )([0-9.+-e]+)(?: \(s\))',
  'atan2':'(?:Average execution time: )([0-9.+-e]+)(?: \(us\))',
  'atomicAggregate':'(?:Total kernel time \(32 locations\): )([0-9.+-e]+)(?: \(s\))',
  'atomicCAS':'(?:Average execution time: )([0-9.+-e]+)(?: \(s\))',
  'atomicCost':'(?:Average execution time of WithoutAtomicOnGlobalMem: )([0-9.+-e]+)(?: \(us\))',
  'atomicIntrinsics':'(?:Average kernel execution time )([0-9.+-e]+)(?: \(us\))',
  'atomicPerf':'(?:Average execution time of [A-Za-z]+: )([0-9.+-e]+)(?: \(us\))',
  'atomicReduction':'(?:The average performance of reduction is )([0-9.+-e]+)(?: GBytes/sec)',
  'atomicSystemWide':'(?:Execution time of atomic kernels on host and device: )([0-9.+-e]+)(?: \(s\))',
  'attention':'(?:Average execution time of kernels )([0-9.+-e]+)(?: \(ms\))',
  'attentionMultiHead':'(?:Average kernel execution time: )([0-9.+-e]+)(?: \(us\))',
  'axhelm':'(?:elapsed time=)([0-9.+-e]+)',
  'b+tree':'(?:Kernel execution time: )([0-9.+-e]+)(?: \(us\))',
  'babelstream':'(?:Triad       )([0-9.+-e]+)',
  'background-subtract':'(?:Average kernel execution time: )([0-9.+-e]+)(?: \(us\))',
  'backprop':'(?:time = )([0-9.+-e]+)(?:\(s\))',
  'bezier-surface':'(?:kernel execution time: )([0-9.+-e]+)(?: ms)',
  'bfs':'(?:Total kernel execution time : )([0-9.+-e]+)(?: \(us\))',
  'bh':'(?:Total kernel execution time: )([0-9.+-e]+)(?: s)',
  'bicgstab':'(?:Total execution time of BiCGStab: )([0-9.+-e]+)(?: \(s\))',
  'bilateral':'(?:Average kernel execution time \([1-9]x[1-9]\) )([0-9.+-e]+)(?: \(ms\))',
  'bincount':'(?:Average execution time of bincount kernel: )([0-9.+-e]+)(?: \(us\))',
  'binomial':'(?:Total binomialOptionsGPU\(\) time: )([0-9.+-e]+)(?: msec)',
  'bitcracker':'(?:Total kernel time \(decrypt_vmk_with_mac\): )([0-9.+-e]+)(?: s)',
  'bitonic-sort':'(?:Total kernel execution time: )([0-9.+-e]+)(?: \(ms\))',
  'bitpacking':'(?:Device offload time = )([0-9.+-e]+)(?: \((?:s|ms|us)\))',
  'bitpermute':'(?:Average execution time of the kernel: )([0-9.+-e]+)(?: \(us\))',
  'black-scholes':'(?:Processing time on GPU: )([0-9.+-e]+)(?: \(ms\))',
  'blas-dot':'(?:Average cublasDotEx execution time )([0-9.+-e]+)(?: \(ms\))',
  'blas-fp8gemm':'(?:Average cublasLtMatmul execution time )([0-9.+-e]+)(?: \(us\))',
  'blas-gemm':'(?:Average GEMM execution time: )([0-9.+-e]+)(?: \(us\))',
  'blas-gemmBatched':'(?:average execution time: )([0-9.+-e]+)(?: us)',
  'blas-gemmEx':'([0-9.+-e]+)(?: TOP/s)',
  'blas-gemmEx2':'([0-9.+-e]+)(?: TOP/s)',
  'blas-gemmStridedBatched':'(?:average execution time: )([0-9.+-e]+)(?: us)',
  'blockAccess':'(?:Average execution time of the [A-Za-z]+ [A-Za-z]+: )([0-9.+-e]+)(?: \(us\))',
  'blockexchange':'(?:Average execution time of kernel: )([0-9.+-e]+)(?: \(us\))',
  'bm3d':'',
  'bmf':'(?:elapsed time \(GPUKERNELLOOP\): )([0-9.+-e]+)(?:s)',
  'bn':'(?:Average execution time of genScoreKernel: )([0-9.+-e]+)(?: \(s\))',
  'bonds':'(?:Average processing time on GPU: )([0-9.+-e]+)(?: \(ms\))',
  'boxfilter':'(?:Average kernel execution time )([0-9.+-e]+)(?: \(us\))',
  'bscan':'(?:Average execution time: )([0-9.+-e]+)(?: \(us\))',
  'bsearch':'(?:Average kernel execution time \(bs[1-9]\) )([0-9.+-e]+)(?: \(s\))',
  'bspline-vgh':'(?:Total kernel execution time )([0-9.+-e]+)(?: \(s\))',
  'bsw':'(?:Total loop iteration time \(seconds\):)([0-9.+-e]+)',
  'btree':'(?:Total device execution time = )([0-9.+-e]+)(?: s)',
  'burger':'(?:Total kernel execution time )([0-9.+-e]+)(?: \(s\))',
  'bwt':'(?:Device time: )([0-9.+-e]+)(?: (?:s|ms|us))',
  'car':'(?:Average kernel execution time )([0-9.+-e]+)(?: \(s\))',
  'cbsfil':'(?:Average kernel execution time )([0-9.+-e]+)(?: \(s\))',
  'cc':'(?:Average kernel execution time: )([0-9.+-e]+)(?: s)',
  'ccl':'',
  'ccs':'(?:Average kernel execution time )([0-9.+-e]+)(?: \(s\))',
  'ccsd-trpdrv':'(?:avg=)([0-9.+-e]+)',
  'ced':'(?:Total time )([0-9.+-e]+)(?: secs)',
  'cfd':'(?:Total execution time of kernels = )([0-9.+-e]+)(?:\(s\))',
  'chacha20':'(?:Average execution time of kernels: )([0-9.+-e]+)(?: \(us\))',
  'channelShuffle':'(?:Average time of channel shuffle \(\w+\): )([0-9.+-e]+)(?: \(ms\))',
  'channelSum':'(?:Average time of channel sum \(\w+\): )([0-9.+-e]+)(?: \(ms\))',
  'che':'(?:Kernel exeuction time on the GPU \([0-9]+ iterations\) = )([0-9.+-e]+)(?: \(s\))',
  'chemv':'(?:Average execution time of chemv kernels: )([0-9.+-e]+)(?: \(us\))',
  'chi2':'(?:Average kernel execution time = )([0-9.+-e]+)(?: \(s\))',
  'clenergy':'(?:Kernel time: )([0-9.+-e]+)(?: seconds)',
  'clink':'(?:Average kernel time: )([0-9.+-e]+)(?: ms)',
  'clock':'(?:Total clocks = )([0-9.+-e]+)',
  'cm':'',
  'cmembench':'(?:Average kernel execution time \(memory access width = [0-9]+ bytes\): )([0-9.+-e]+)(?: ms)',
  'cmp':'',
  'cobahh':'(?:Average kernel execution time )([0-9.+-e]+)(?: \(us\))',
  'collision':'(?:Average execution time of the function [A-Za-z_]+: )([0-9.+-e]+)(?: \(us\))',
  'colorwheel':'(?:Average kernel execution time : )([0-9.+-e]+)(?: \(ms\))',
  'columnarSolver':'',
  'complex':'(?:Average kernel execution time \([a-z]+\) )([0-9.+-e]+)(?: \(s\))',
  'compute-score':'(?:Kernel Time = )([0-9.+-e]+)(?: ms)',
  'concat':'(?:Average kernel execution time: )([0-9.+-e]+)(?: \(us\))',
  'concurrentKernels':'(?:Measured time for sample = )([0-9.+-e]+)(?:s)',
  'contract':'(?:Average kernel execution time )([0-9.+-e]+)(?: \(s\))',
  'conversion':'(?:average time\(sec\):)([0-9.+-e]+)(?:,)',
  'convolution1D':'(?:Average kernel execution time of conv1d[-\sA-Za-z]+ kernel: )([0-9.+-e]+)(?: \(us\))',
  'convolution3D':'Average kernel execution time of conv3d_[A-Za-z0-9]+ kernel: ([0-9.+-e]+)(?: \(us\))',
  'convolutionDeformable':'',
  'convolutionSeparable':'(?:Average kernel execution time )([0-9.+-e]+)(?: \(s\))',
  'cooling':'(?:Average kernel execution time )([0-9.+-e]+)(?: \((?:s|ms|us)\))',
  'coordinates':'(?:Average execution time of [A-Za-z]+ transform: )([0-9.+-e]+)(?: \(us\))',
  'copy':'(?:| Total time: )([0-9.+-e]+)(?: ms)',
  'crc64':'([0-9.+-e]+)(?: MB\/s)',
  'cross':'(?:Average execution time of cross[0-9]+ kernel: )([0-9.+-e]+)(?: \((?:s|ms|us)\))',
  'crossEntropy':'(?:Average GPU kernel time \(ms\) : )([0-9.+-e]+)',
  'crs':'(?:Total encoding time )([0-9.+-e]+)(?: \(s\))',
  'd2q9-bgk':'(?:average kernel execution time over [0-9]+ iterations:[\s]+)([0-9.+-e]+)(?: \(us\))',
  'd3q19-bgk':'',
  'damage':'(?:Average kernel execution time )([0-9.+-e]+)(?: \((?:s|ms|us)\))',
  'daphne':'(?:Elapsed time: )([0-9.+-e]+)(?: seconds)',
  'dct8x8':'(?:Average DCT8x8 kernel execution time )([0-9.+-e]+)(?: \(s\))',
  'ddbp':'(?:Total kernel execution )([0-9.+-e]+)(?: \(s\))',
  'debayer':'(?:Average kernel execution time )([0-9.+-e]+)(?: \(s\))',
  'degrid':'(?:Average kernel execution time )([0-9.+-e]+)(?: \(s\))',
  'dense-embedding':'(?:Average execution time of dense embedding kernel \(k2\): )([0-9.+-e]+)(?: \(us\))',
  'depixel':'(?:Average kernel time over [0-9]+ iterations: )([0-9.+-e]+)(?: \(s\))',
  'deredundancy':'(?:Device offload time )([0-9.+-e]+)(?: secs)',
  'determinant':'(?:Average execution time: )([0-9.+-e]+)(?: \(us\))',
  'diamond':'',
  'dispatch':'(?:mean = )([0-9.+-e]+)(?: us)',
  'distort':'(?:Average kernel execution time: )([0-9.+-e]+)(?: \(ms\))',
  'divergence':'(?:Total Time: )([0-9.+-e]+)',
  'doh':'Average kernel execution time : ([0-9.+-e]+)(?: \(us\))',
  'dp':'(?:Average [A-Za-z:_\s]+)([0-9.+-e]+)(?: \(s\))',
  'dpid':'(?:Average kernel execution time )([0-9.+-e]+)(?: \(s\))',
  'dropout':'(?:Total kernel execution time \(VEC[0-9]\) )([0-9.+-e]+)(?: \(s\))',
  'dslash':'(?:Total GFLOP/s = )([0-9.+-e]+)',
  'dwconv':'(?:Average execution time of dwconv2d_forward kernel: )([0-9.+-e]+)(?: \(ms\))',
  'dwconv1d':'',
  'dxtc1':'(?:Average kernel execution time )([0-9.+-e]+)(?: \(s\))',
  'dxtc2':'(?:Average kernel execution time )([0-9.+-e]+)(?: \(us\))',
  'easyWave':'(?:elapsed: )([0-9.+-e]+)(?: msec)',
  'ecdh':'(?:: )([0-9.+-e]+)(?: s)',
  'egs':'(?:Elapsed time [\s.]+)([0-9.+-e]+)(?: ms)',
  'eigenvalue':'(?:Average kernel execution time )([0-9.+-e]+)(?: \(us\))',
  'eikonal':'(?:Total Running Time: )([0-9.+-e]+)(?: \(sec\))',
  'entropy':'(?:execution time )([0-9.+-e]+)(?: \(s\))',
  'epistasis':'(?:Average kernel execution time: )([0-9.+-e]+)(?: \(s\))',
  'ert':'(?:runtime \([a-z1-9]*\): )([0-9.+-e]+)(?: \(s\))',
  'expdist':'(?:Average kernel execution time )([0-9.+-e]+)(?: \(s\))',
  'extend2':'(?:Average offload time )([0-9.+-e]+)(?: \(us\))',
  'extrema':'(?:Total kernel execution time: )([0-9.+-e]+)(?: \(s\))',
  'f16max':'(?:Average kernel execution time )([0-9.+-e]+)(?: \(us\))',
  'f16sp':'(?:Average kernel execution time )([0-9.+-e]+)(?: \(us\))',
  'face':'(?:Object detection time )([0-9.+-e]+)(?: \(s\))',
  'fdtd3d':'(?:Average kernel execution time )([0-9.+-e]+)(?: \((?:s|ms|us)\))',
  'feynman-kac':'(?:Average kernel time: )([0-9.+-e]+)(?: \((?:s|ms|us)\))',
  'fft':'(?:Average kernel execution time )([0-9.+-e]+)(?: \(s\))',
  'fhd':'(?:Device execution time )([0-9.+-e]+)(?: \(s\))',
  'filter':'(?:Average execution time of filter \(shared memory\) )([0-9.+-e]+)(?: \(ms\))',
  'flame':'(?:Total frame time is )([0-9.+-e]+)(?: us)',
  'flip':'(?:Average execution time of the flip kernel: )([0-9.+-e]+)(?: \(ms\))',
  'floydwarshall':'(?:Average kernel execution time )([0-9.+-e]+)(?: \(s\))',
  'floydwarshall2':'(?:Average kernel \([A-Za-z]+\) time:\s+)([0-9.+-e]+)(?: s)',
  'fluidSim':'(?:Average kernel execution time )([0-9.+-e]+)(?: \(s\))',
  'fpc':'(?:fpc2: average device offload time )([0-9.+-e]+)(?: \(s\))',
  'fpdc':'(?:Average compression kernel execution time )([0-9.+-e]+)(?: \(s\))',
  'frechet':'(?:Average kernel execution time )([0-9.+-e]+)(?: \(s\))',
  'fresnel':'(?:Average kernel execution time )([0-9.+-e]+)(?: \(s\))',
  'frna':'(?:Total kernel execution time )([0-9.+-e]+)(?: \(s\))',
  'fsm':'([0-9.+-e]+)(?:\s*#runtime \[s\])',
  'fwt':'(?:Average device execution time )([0-9.+-e]+)(?: \(s\))',
  'ga':'(?:Total kernel execution time )([0-9.+-e]+)(?: \(s\))',
  'gabor':'(?:Average kernel execution time: )([0-9.+-e]+)(?: \(us\))',
  'gamma-correction':'(?:Average kernel execution time )([0-9.+-e]+)(?: \(s\))',
  'gaussian':'(?:Device offloading time )([0-9.+-e]+)(?: \(us\))',
  'gc':'(?:average runtime \([0-9]+ runs\):\s+)([0-9.+-e]+)(?: s)',
  'gd':'(?:Training time takes )([0-9.+-e]+)(?: \(s\))',
  'ge-spmm':'(?:Average kernel \(method [0-9]\) execution time )([0-9.+-e]+)(?: \(us\))',
  'geam':'(?:matrix transpose time = )([0-9.+-e]+)(?: \(ms\))',
  'gels':'(?:Average kernel execution time : )([0-9.+-e]+)(?: \(us\))',
  'gelu':'(?:Average kernel execution time )([0-9.+-e]+)(?: \(ms\))',
  'gemv':'(?:Average kernel execution time: )([0-9.+-e]+)(?: \(us\))',
  'geodesic':'(?:Average kernel execution time )([0-9.+-e]+)(?: \(s\))',
  'gerbil':'(?:time \(real\) total \(1 \+ 2\) :\s+)([0-9.+-e]+)(?: s)',
  'gibbs':'(?:Average execution time of kernels: )([0-9.+-e]+)(?: \(us\))',
  'glu':'(?:Average execution time of GLU kernel \(split dimension = 2\): )([0-9.+-e]+)(?: \(us\))',
  'gmm':'(?:Execution time of the cluster function )([0-9.+-e]+)(?: \(s\))',
  'goulash':'(?:total kernel time )([0-9.+-e]+)(?:\(s\))',
  'gpp':'(?:Average kernel execution time )([0-9.+-e]+)(?: \(s\))',
  'graphB+':'(?:Total graphB\+ runtime:\s+)([0-9.+-e]+)(?: s)',
  'graphExecution':'(?:Execution time: )([0-9.+-e]+)(?: \(us\))',
  'grep':'',
  'grrt':'(?:Total kernel execution time \(task[0-9]+\) )([0-9.+-e]+)(?: \(s\))',
  'gru':'(?:Average execution time of gru_cell_forward: )([0-9.+-e]+)(?: \(us\))',
  'haccmk':'(?:Average kernel execution time )([0-9.+-e]+)(?: \(s\))',
  'halo-finder':'',
  'hausdorff':'(?:Average execution time of kernels: )([0-9.+-e]+)(?: \(ms\))',
  'haversine':'',
  'hbc':'',
  'heartwall':'',
  'heat':'',
  'heat2d':'',
  'hellinger':'',
  'henry':'',
  'hexciton':'',
  'histogram':'(?:Avg time )([0-9.+-e]+)(?: us )',
  'hmm':'(?:Device execution time of Viterbi iterations )([0-9.+-e]+)(?: \(s\))',
  'hogbom':'',
  'hotspot':'',
  'hotspot3D':'',
  'hpl':'',
  'hungarian':'',
  'hwt1d':'(?:Average device offload time )([0-9.+-e]+)(?: \(s\))',
  'hybridsort':'(?:GPU execution time: )([0-9.+-e]+)(?: ms)',
  'hypterm':'',
  'idivide':'',
  'interleave':'',
  'interval':'',
  'intrinsics-cast':'',
  'intrinsics-simd':'',
  'inversek2j':'(?:Average kernel execution time )([0-9.+-e]+)(?: \(us\))',
  'is':'',
  'ising':'(?:elapsed time: )([0-9.+-e]+)(?: sec)',
  'iso2dfd':'(?:Total kernel execution time )([0-9.+-e]+)(?: \(ms\))',
  'jaccard':'',
  'jacobi':'(?:Total elapsed time: )([0-9.+-e]+)(?: seconds)',
  'jenkins-hash':'(?:Average kernel execution time : )([0-9.+-e]+)(?: \(s\))',
  'kalman':'',
  'keccaktreehash':'',
  'keogh':'',
  'kernelLaunch':'',
  'kmc':'',
  'kmeans':'',
  'knn':'',
  'kurtosis':'',
  'lanczos':'',
  'langevin':'',
  'langford':'',
  'laplace':'(?:iterations: )([0-9.+-e]+)(?: s)',
  'laplace3d':'',
  'lavaMD':'(?:Device offloading time:\s)([0-9.+-e]+)(?: s)',
  'layernorm':'',
  'layout':'(?:Average kernel execution time \(SoA\): )([0-9.+-e]+)(?: \(us\))',
  'lci':'',
  'lda':'',
  'ldpc':'',
  'lebesgue':'',
  'leukocyte':'',
  'lfib4':'',
  'libor':'(?:Average kernel execution time : )([0-9.+-e]+)(?: \(s\))',
  'lid-driven-cavity':'',
  'lif':'(?:Average kernel execution time: )([0-9.+-e]+)(?: \(us\))',
  'linearprobing':'(?:Kernel execution time \(iterate\): )([0-9.+-e]+)(?: \(s\))',
  'log2':'',
  'logan':'',
  'logic-resim':'',
  'logic-rewrite':'',
  'logprob':'(?:Average execution time of kernels: )([0-9.+-e]+)(?: \(us\))',
  'lombscargle':'(?:Average kernel execution time )([0-9.+-e]+)(?: \(us\))',
  'loopback':'',
  'lr':'',
  'lrn':'',
  'lsqt':'',
  'lud':'',
  'ludb':'',
  'lulesh':'',
  'lzss':'',
  'mallocFree':'',
  'mandelbrot':'(?:Average kernel execution time: )([0-9.+-e]+)(?: ms)',
  'marchingCubes':'',
  'mask':'(?:Average execution time of \w+ kernel: )([0-9.+-e]+)(?: \(us\))',
  'match':'',
  'matern':'',
  'matrix-rotate':'(?:Average kernel execution time: )([0-9.+-e]+)(?: \(s\))',
  'matrixT':'',
  'maxFlops':'',
  'maxpool3d':'(?:Average kernel execution time: )([0-9.+-e]+)(?: \(s\))',
  'mcmd':'',
  'mcpr':'',
  'md':'(?:Average kernel execution time )([0-9.+-e]+)(?: \(s\))',
  'md5hash':'',
  'mdh':'',
  'meanshift':'(?:Average execution time of mean-shift \(opt\) )([0-9.+-e]+)(?: ms)',
  'medianfilter':'(?:Average kernel execution time: )([0-9.+-e]+)(?: \(s\))',
  'memcpy':'',
  'memtest':'',
  'merge':'(?:Average kernel execution time: )([0-9.+-e]+)(?: \(us\))',
  'merkle':'(?: )([0-9.+-e]+)(?: ms)',
  'metropolis':'(?:Total kernel time \(metropolis simulation\) )([0-9.+-e]+)(?: secs)',
  'mf-sgd':'',
  'michalewicz':'(?:Average execution time of kernel \(dim = [0-9]+\): )([0-9.+-e]+)(?: \(us\))',
  'miniDGS':'',
  'miniFE':'',
  'miniWeather':'',
  'minibude':'(?:Total kernel time:\s+)([0-9.+-e]+)(?: ms)',
  'minimap2':'(?:Total kernel execution time: )([0-9.+-e]+)(?: \(s\))',
  'minimod':'(?:Average kernel time per iteration: )([0-9.+-e]+)(?: s)',
  'minisweep':'(?:kernel time: )([0-9.+-e]+)(?: \(s\))',
  'minkowski':'(?:Average kernel execution time: )([0-9.+-e]+)(?: \(s\))',
  'minmax':'(?:Average execution time of thrust.*: )([0-9.+-e]+)(?: \(us\))',
  'mis':'(?:compute time: )([0-9.+-e]+)(?: s)',
  'mixbench':'(?:Total kernel execution time: )([0-9.+-e]+)(?: \(s\))',
  'mmcsf':'(?:Total GPU time: )([0-9.+-e]+)(?: sec)',
  'mnist':'(?:Total time \(learn \+ test\) )([0-9.+-e]+)(?: secs)',
  'morphology':'(?:Average kernel execution time \([A-Za-z]+\): )([0-9.+-e]+)(?: \(s\))',
  'mpc':'(?:compression time: )([0-9.+-e]+)(?: ms)',
  'mr':'(?:Total kernel execution time \(\w+\s*\): )([0-9.+-e]+)(?: \(ms\))',
  'mrc':'(?:Average execution time of MRC2* kernel: )([0-9.+-e]+)(?: \(us\))',
  'mrg32k3a':'(?:Average execution time on \w+: )([0-9.+-e]+)(?: \(us\))',
  'mriQ':'(?:compute\w+ time: )([0-9.+-e]+)(?: s)',
  'mt':'(?:Time = )([0-9.+-e]+)(?: s)',
  'mtf':'(?:Average execution time: )([0-9.+-e]+)(?: \(s\))',
  'multimaterial':'(?:Compact matrix, cell centric, alg [0-9]+: )([0-9.+-e]+)(?: msec)',
  'multinomial':'(?:Average execution time of sampleMultinomialOnce kernel: )([0-9.+-e]+)(?: \(us\))',
  'murmurhash3':'(?:Average kernel execution time )([0-9.+-e]+)(?: \(s\))',
  'myocyte':'(?:Total kernel execution time )([0-9.+-e]+)(?: \(s\))',
  'nbnxm':'(?:Average kernel execution time \(w/o shift\): )([0-9.+-e]+)(?: \(us\))',
  'nbody':'(?:Total Time \(s\)[ ]*: )([0-9.+-e]+)',
  'ne':'(?:Average kernel execution time: )([0-9.+-e]+)(?: \(s\))',
  'nlll':'(?:Average execution time of nll loss forward reduce 2D kernel: )([0-9.+-e]+)(?: \(us\))',
  'nms':'(?:Average kernel execution time \(.+\: )([0-9.+-e]+)(?: \(s\))',
  'nn':'(?:Average kernel execution time: )([0-9.+-e]+)(?: \(us\))',
  'nonzero':'(?:Average time for .+: )([0-9.+-e]+)(?: \(us\))',
  'norm2':'(?:execution time = )([0-9.+-e]+)(?: \(us\))',
  'nosync':'(?:Average execution time: )([0-9.+-e]+)(?: \(us\))',
  'nqueen':'(?:Average kernel execution time: )([0-9.+-e]+)(?: \(s\))',
  'ntt':'(?:Average kernel execution time: )([0-9.+-e]+)(?: \(us\))',
  'nw':'(?:Total kernel execution time: )([0-9.+-e]+)(?: \(s\))',
  'openmp':'(?:Work took )([0-9.+-e]+)(?: seconds)',
  'opticalFlow':'(?:Processing time on \w+: )([0-9.+-e]+)(?: \(ms\))',
  'overlap':'(?:Avg. time when overlapped using [0-9]+ streams.*: )([0-9.+-e]+)(?: ms)',
  'overlay':'',
  'p2p':'',
  'p4':'(?:Average execution time of postprocess kernel: )([0-9.+-e]+)(?: \(us\))',
  'pad':'(?:Total padding execution time for [0-9.+-e]+ iterations: )([0-9.+-e]+)(?: \((?:s|ms|us)\))',
  'page-rank':'(?:Total kernel execution time: )([0-9.+-e]+)(?: \(s\))',
  'particle-diffusion':'(?:Average kernel execution time: )([0-9.+-e]+)(?: \(s\))',
  'particlefilter':'(?:Device offloading time: )([0-9.+-e]+)(?: \(s\))',
  'particles':'(?:Total execution time of [0-9]+ loop iterations: )([0-9.+-e]+)(?: \(s\))',
  'pathfinder':'(?:Device offloading time = )([0-9.+-e]+)(?: \(s\))',
  'pcc':'([0-9.+-e]+)(?: \(s\))',
  'perlin':'(?:Total kernel execution time )([0-9.+-e]+)(?: \(ms\))',
  'permutate':'(?:Execution time of the permutation testing processed in the GPU : )([0-9.+-e]+)(?: sec)',
  'permute':'(?:time )([0-9.+-e]+)(?: ms)',
  'perplexity':'(?:Average kernel execution time: )([0-9.+-e]+)(?: \(s\))',
  'phmm':'(?:Total execution time )([0-9.+-e]+)(?: milliseconds)',
  'pingpong':'',
  'pitch':'(?:Average execution time \(pitched vs simple\): )([0-9.+-e]+)',
  'pnpoly':'(?:Average kernel execution time \(.+\): )([0-9.+-e]+)(?: \(s\))',
  'pns':'(?:Total device execution time: )([0-9.+-e]+)(?: s)',
  'pointwise':'(?:Average kernel execution time: )([0-9.+-e]+)(?: \(s\))',
  'pool':'(?:Average kernel execution time: )([0-9.+-e]+)(?: \(s\))',
  'popcount':'(?:Average kernel execution time \(pc[0-9]+\): )([0-9.+-e]+)(?: \(us\))',
  'prefetch':'(?:Average execution time: )([0-9.+-e]+)(?: \(ms\))',
  'present':'(?:Average kernel execution time: )([0-9.+-e]+)(?: \(us\))',
  'prna':'',
  'projectile':'(?:Average kernel execution time: )([0-9.+-e]+)(?: \(s\))',
  'pso':'(?:Average kernel execution time )([0-9.+-e]+)(?: \(us\))',
  'qem':'(?:Execution time \(ms\): )([0-9.+-e]+)',
  'qkv':'(?:time )([0-9.+-e]+)(?: ms)',
  'qrg':'(?:Average kernel execution time \(.+\): )([0-9.+-e]+)(?: \(us\))',
  'qtclustering':'(?:total: )([0-9.+-e]+)(?: \(s\))',
  'quicksort':'(?:Time to sort: )([0-9.+-e]+)(?: ms)',
  'radixsort':'(?:Average execution time of radixsort: )([0-9.+-e]+)(?: \(s\))',
  'radixsort2':'(?:Time = )([0-9.+-e]+)(?: s)',
  'rainflow':'(?:Average kernel execution time: )([0-9.+-e]+)(?: \(us\))',
  'randomAccess':'(?:Average kernel execution time: )([0-9.+-e]+)(?: \(s\))',
  'rayleighBenardConvection':'(?:Total compute time: )([0-9.+-e]+)(?: \(s\))',
  'reaction':'(?:Total kernel execution time:\s+)([0-9.+-e]+)(?: s)',
  'recursiveGaussian':'(?:Average execution time of kernels: )([0-9.+-e]+)(?: \(s\))',
  'relu':'(?:Average execution time of .+: )([0-9.+-e]+)(?: \(us\))',
  'remap':'(?:Average execution time of .+: )([0-9.+-e]+)(?: \(us\))',
  'resize':'(?:Average kernel execution time: )([0-9.+-e]+)(?: \(us\))',
  'resnet-kernels':'(?:Average device offload time: \[)([0-9.+-e]+)(?: us\])',
  'reverse':'(?:Total kernel execution time: )([0-9.+-e]+)(?: \(s\))',
  'reverse2D':'(?:Average kernel execution time: )([0-9.+-e]+)(?: \(ms\))',
  'rfs':'(?:Average kernel execution time \(sumArray\): )([0-9.+-e]+)(?: \(s\))',
  'ring':'(?:Average total exchange time: )([0-9.+-e]+)(?: \(us\))',
  'rle':'(?:, )([0-9.+-e]+)(?: avg ms)',
  'rng-wallace':'(?:Average kernel execution time: )([0-9.+-e]+)(?: \(s\))',
  'rodrigues':'(?:Average kernel execution time \(float[0-9]\): )([0-9.+-e]+)(?: \(us\))',
  'romberg':'(?:Average kernel execution time: )([0-9.+-e]+)(?: \(s\))',
  'rotary':'(?:Average execution time: )([0-9.+-e]+)(?: \(us\))',
  'rowwiseMoments':'',
  'rsbench':'(?:Runtime:\s+)([0-9.+-e]+)(?: seconds)',
  'rsc':'(?:Total task execution time for [0-9.+-e]+ iterations: )([0-9.+-e]+)(?: \((?:s|ms|us)\))',
  'rsmt':'(?:compute time: )([0-9.+-e]+)(?: s)',
  'rtm8':'(?:average kernel execution time = )([0-9.+-e]+)(?: \(s\))',
  'rushlarsen':'(?:Device: computed [0-9]+ time steps in )([0-9.+-e]+)(?: s)',
  's3d':'(?:Total time )([0-9.+-e]+)(?: secs)',
  's8n':'(?:Average execution time of select[0-9]* kernel: )([0-9.+-e]+)(?: \(us\))',
  'sa':'(?:Average suffix array construct time \(input size = [0-9]+\): )([0-9.+-e]+)(?: \(s\))',
  'sad':'(?:Elapsed time in msec: )([0-9.+-e]+)',
  'sampling':'(?:Average execution time of kernels: )([0-9.+-e]+)(?: \(us\))',
  'saxpy-ompt':'',
  'sc':'(?:Total stream compaction time for [0-9.+-e]+ iterations: )([0-9.+-e]+)(?: \((?:s|ms|us)\))',
  'scan':'(?:Average execution time of scan \(.+\): )([0-9.+-e]+)(?: \(us\))',
  'scan2':'(?:Average execution time of scan kernels: )([0-9.+-e]+)(?: \(us\))',
  'scan3':'(?:Average execution time of .+ exclusive scan: )([0-9.+-e]+)(?: \(us\))',
  'scel':'(?:Average execution time of SigmoidCrossEntropyWithLogits kernel: )([0-9.+-e]+)(?: \(us\))',
  'score':'(?:Average kernel execution time: )([0-9.+-e]+)(?: \(ms\))',
  'sddmm-batch':'(?:Average execution time of SDDMM: )([0-9.+-e]+)(?: \(us\))',
  'seam-carving':'(?:Execution time of seam carver kernels: )([0-9.+-e]+)(?: \(ms\))',
  'secp256k1':'(?:Average kernel execution time: )([0-9.+-e]+)(?: \(s\))',
  'segment-reduce':'(?:Throughput = )([0-9.+-e]+)(?: \(G/s\))',
  'segsort':'(?:Kernel execution time: )([0-9.+-e]+)(?: \(s\))',
  'sheath':'(?:Time per time step: )([0-9.+-e]+)(?: \(ms\))',
  'shmembench':'(?:Average kernel execution time : )([0-9.+-e]+)(?: \(ms\))',
  'shuffle':'(?:Average kernel time \(subgroup size = [0-9]+\): )([0-9.+-e]+)(?: \(us\))',
  'si':'',
  'simpleMultiDevice':'(?:Average GPU Processing time: )([0-9.+-e]+)(?: \(us\))',
  'simpleSpmv':'(?:Average dense, sparse, and vector sparse kernel execution time \(ms\): )([0-9.+-e]+)',
  'simplemoc':'(?:Total kernel time:       )([0-9.+-e]+)(?: seconds)',
  'slit':'(?:Average execution time of FFT: )([0-9.+-e]+)(?: ms)',
  'slu':'',
  'snake':'(?:Average kernel time \(us\): )([0-9.+-e]+)',
  'sobel':'(?:Average kernel execution time: )([0-9.+-e]+)',
  'sobol':'(?:Average kernel execution time: )([0-9.+-e]+)(?: \(s\))',
  'softmax':'(?:Average kernel execution time: )([0-9.+-e]+)(?: \(ms\))',
  'softmax-fused':'(?:Average kernel execution time: )([0-9.+-e]+)(?: \(ms\))',
  'softmax-online':'(?:time )([0-9.+-e]+)(?: ms)',
  'sort':'(?:Average elapsed time of sort: )([0-9.+-e]+)(?: \(s\))',
  'sortKV':'(?:Average sort time )([0-9.+-e]+)(?: \(us\))',
  'sosfil':'(?:Average kernel execution time )([0-9.+-e]+)(?: \(s\))',
  'sparkler':'',
  'spaxpby':'(?:Average execution time of SPAXPBY : )([0-9.+-e]+)(?: \(us\))',
  'spd2s':'(?:Average execution time of DenseToSparse_convert : )([0-9.+-e]+)(?: \(us\))',
  'spgeam':'(?:Average execution time of cuSparse csr2cscEx2 : )([0-9.+-e]+)(?: \(us\))',
  'spgemm':'(?:Average execution time of SPGEMM \(.+\) compute: )([0-9.+-e]+)(?: \(us\))',
  'sph':'(?:Average execution time of sph kernels: )([0-9.+-e]+)(?: \(ms\))',
  'split':'(?:Average kernel execution time: )([0-9.+-e]+)(?: \(us\))',
  'spm':'(?:Average kernel execution time: )([0-9.+-e]+)(?: \(ms\))',
  'spmm':'(?:Average execution time of SPMM compute: )([0-9.+-e]+)(?: \(us\))',
  'spmv':'(?:Average kernel \(.+\) execution time \(ms\): )([0-9.+-e]+)',
  'spnnz':'(?:Average execution time of cusparseSnnz : )([0-9.+-e]+)(?: \(us\))',
  'sps2d':'(?:Average execution time of SparseToDense_convert : )([0-9.+-e]+)(?: \(us\))',
  'spsm':'(?:Average execution time of SpSM solve: )([0-9.+-e]+)(?: \(us\))',
  'spsort':'(?:Average execution time of CSR sort: )([0-9.+-e]+)(?: us)',
  'sptrsv':'(?:Average kernel execution time: )([0-9.+-e]+)(?: \(us\))',
  'srad':'',
  'ss':'(?:Average kernel execution time: )([0-9.+-e]+)(?: \(us\))',
  'ssim':'(?:Total kernel execution time \(s\): )([0-9.+-e]+)',
  'sss':'',
  'sssp':'(?:time \(ms\): )([0-9.+-e]+)',
  'stddev':'(?:Average execution time of stddev kernels: )([0-9.+-e]+)(?: \(s\))',
  'stencil1d':'(?:Average kernel execution time: )([0-9.+-e]+)(?: \(s\))',
  'stencil3d':'(?:Average kernel execution time: )([0-9.+-e]+)(?: \(s\))',
  'streamCreateCopyDestroy':'(?:[0-9]+ buffers  and [0-9\s]+ iterations )([0-9.+-e]+)(?: \(ms\))',
  'streamOrderedAllocation':'(?:Total elapsed time: )([0-9.+-e]+)(?: \(us\))',
  'streamPriority':'(?:Elapsed time of kernel launched to .+priority stream: )([0-9.+-e]+)(?: ms)',
  'streamUM':'(?:Task execution time : )([0-9.+-e]+)(?: \(s\))',
  'streamcluster':'(?:Total time = )([0-9.+-e]+)(?: \(s\))',
  'stsg':'',
  'su3':'(?:Total kernel execution time = )([0-9.+-e]+)(?: \(s\))',
  'surfel':'(?:Average kernel execution time: )([0-9.+-e]+)(?: \(ms\))',
  'svd3x3':'(?:Average kernel execution time: )([0-9.+-e]+)(?: \(us\))',
  'sw4ck':'(?:Average execution time of sw4ck kernels: )([0-9.+-e]+)(?: milliseconds)',
  'swish':'(?:Average execution time of .+kernel: )([0-9.+-e]+)(?: \(us\))',
  'tensorAccessor':'(?:Average execution time of .+: )([0-9.+-e]+)(?: \(us\))',
  'tensorT':'(?:Average kernel execution time: )([0-9.+-e]+)(?: \(ms\))',
  'testSNAP':'(?:Total kernel time = )([0-9.+-e]+)(?: \[msec/step\])',
  'thomas':'(?:Average .+execution time: )([0-9.+-e]+)(?: \(ms\))',
  'threadfence':'(?:Average kernel execution time: )([0-9.+-e]+)(?: \(ms\))',
  'tissue':'(?:Average kernel execution time: )([0-9.+-e]+)(?: \(s\))',
  'tonemapping':'(?:Average kernel execution time: )([0-9.+-e]+)(?: \(us\))',
  'tpacf':'(?:TOTAL time \(DD\+RRS\+DRS\+IO\): )([0-9.+-e]+)(?: sec)',
  'tqs':'(?:Total task execution time for [0-9.+-e]+ iterations: )([0-9.+-e]+)(?: \((?:s|ms|us)\))',
  'triad':'(?:Average TriadFlops )([0-9.+-e]+)(?: GFLOPS\/s)',
  'tridiagonal':'(?:Time = )([0-9.+-e]+)(?: s)',
  'tsa':'',
  'tsne':'',
  'tsp':'(?:Average kernel time: )([0-9.+-e]+)(?: s)',
  'unfold':'(?:Average execution time of unfold backward kernel: )([0-9.+-e]+)(?: \(us\))',
  'urng':'(?:Average kernel execution time: )([0-9.+-e]+)(?: \(us\))',
  'vanGenuchten':'(?:Average kernel execution time: )([0-9.+-e]+)(?: \(s\))',
  'vmc':'(?:Average execution time of kernels: )([0-9.+-e]+)(?: \(s\))',
  'vol2col':'(?:Average execution time of vol2col kernel: )([0-9.+-e]+)(?: \(us\))',
  'vote':'(?:kernel execution time: )([0-9.+-e]+)(?: \(s\))',
  'voxelization':'(?:Average execution time of the .+kernel: )([0-9.+-e]+)(?: \(us\))',
  'warpexchange':'(?:Average execution time of kernel: )([0-9.+-e]+)(?: \(us\))',
  'warpsort':'(?:average kernel execution time: )([0-9.+-e]+)(?: \(us\))',
  'wedford':'(?:Average kernel execution time )([0-9.+-e]+)(?: \(ms\))',
  'winograd':'(?:Total time: )([0-9.+-e]+)(?: s)',
  'wlcpow':'(?:Average kernel execution time: )([0-9.+-e]+)(?: \(us\))',
  'wmma':'',
  'word2vec':'(?:Words/thread/sec: )([0-9.+-e]+)(?:k)',
  'wordcount':'(?:Average time of word count: )([0-9.+-e]+)(?: \(s\))',
  'wsm5':'(?:Average kernel execution time: )([0-9.+-e]+)(?: \(ms\))',
  'wyllie':'(?:Average kernel execution time: )([0-9.+-e]+)(?: \(ms\))',
  'xlqc':'',
  'xsbench':'(?:Runtime:\s+)([0-9.+-e]+)(?: seconds)',
  'zerocopy':'(?:Average kernel execution time: )([0-9.+-e]+)(?: ms)',
  'zeropoint':'(?:Average execution time of zero-point kernel: )([0-9.+-e]+)(?: \(us\))',
  'zmddft':'(?:Average kernel execution time: )([0-9.+-e]+)(?: \(ms\))',
  'zoom':'(?:Average execution time of the zoom\-\w+ kernel: )([0-9.+-e]+)(?: \(us\))'
}

