regexps = {
  'accuracy':'(?:Average execution time of accuracy kernel: )([0-9.+-e]+)(?: \(us\))',
  'ace':'(?:Offload time: )([0-9.+-e]+)(?: \(ms\))',
  'adam':'(?:Average kernel execution time )([0-9.+-e]+)(?: \(ms\))',
  'addBiasResidualLayerNorm':'',
  'adv':'(?:elapsed time=)([0-9.+-e]+)(?: )',
  'aes':'(?:Average kernel execution time )([0-9.+-e]+)(?: \(s\))',
  'affine':'(?:Average kernel execution time )([0-9.+-e]+)(?: \(s\))',
  'aidw':'(?:Average execution time of AIDW_Kernel_Tiled )([0-9.+-e]+)(?: \(s\))',
  'aligned-types':'(?:Avg. time: )([0-9.+-e]+)(?: ms)',
  'all-pairs-distance':'(?:Average kernel execution time \(w/o? shared memory\): )([0-9.+-e]+)(?: \(us\))',
  'allreduce':'',
  'amgmk':'(?:Total Wall time = )([0-9.+-e]+)(?: seconds.)',
  'ans':'(?:Total elapsed time )([0-9.+-e]+)(?: \(s\))',
  'aobench':'(?:Average render time: )([0-9.+-e]+)(?: sec)',
  'aop':'(?:elapsed time for each run *: )([0-9.+-e]+)(?:ms)',
  'asmooth':'(?:Average filtering time )([0-9.+-e]+)(?: \(s\))',
  'assert':'(?:Kernel time : )([0-9.+-e]+)',
  'asta':'(?:Average kernel execution time )([0-9.+-e]+)(?: \(s\))',
  'atan2':'(?:Average execution time: )([0-9.+-e]+)(?: \(us\))',
  'atomicAggregate':'(?:Total kernel time \(32 locations\): )([0-9.+-e]+)(?: \(s\))',
  'atomicCAS':'(?:Average execution time: )([0-9.+-e]+)(?: \(s\))',
  'atomicCost':'(?:Average execution time of WithoutAtomicOnGlobalMem: )([0-9.+-e]+)(?: \(us\))',
  'atomicIntrinsics':'(?:Average kernel execution time )([0-9.+-e]+)(?: \(us\))',
  'atomicPerf':'(?:Average execution time of [A-Za-z]+: )([0-9.+-e]+)(?: \(us\))',
  'atomicReduction':'(?:The average performance of reduction is )([0-9.+-e]+)(?: GBytes/sec)',
  'atomicSystemWide':'(?:Execution time of atomic kernels on host and device: )([0-9.+-e]+)(?: \(s\))',
  'attention':'(?:Average execution time of kernels )([0-9.+-e]+)(?: \(ms\))',
  'attentionMultiHead':'(?:Average kernel execution time: )([0-9.+-e]+)(?: \(us\))',
  'axhelm':'(?:elapsed time=)([0-9.+-e]+)',
  'b+tree':'(?:Kernel execution time: )([0-9.+-e]+)(?: \(us\))',
  'babelstream':'(?:Triad       )([0-9.+-e]+)',
  'background-subtract':'(?:Average kernel execution time: )([0-9.+-e]+)(?: \(us\))',
  'backprop':'(?:time = )([0-9.+-e]+)(?:\(s\))',
  'bezier-surface':'(?:kernel execution time: )([0-9.+-e]+)(?: ms)',
  'bfs':'(?:Total kernel execution time : )([0-9.+-e]+)(?: \(us\))',
  'bh':'(?:Total kernel execution time: )([0-9.+-e]+)(?: s)',
  'bicgstab':'(?:Total execution time of BiCGStab: )([0-9.+-e]+)(?: \(s\))',
  'bilateral':'(?:Average kernel execution time \([1-9]x[1-9]\) )([0-9.+-e]+)(?: \(ms\))',
  'bincount':'(?:Average execution time of bincount kernel: )([0-9.+-e]+)(?: \(us\))',
  'binomial':'(?:Total binomialOptionsGPU\(\) time: )([0-9.+-e]+)(?: msec)',
  'bitcracker':'(?:Total kernel time \(decrypt_vmk_with_mac\): )([0-9.+-e]+)(?: s)',
  'bitonic-sort':'(?:Total kernel execution time: )([0-9.+-e]+)(?: \(ms\))',
  'bitpacking':'(?:Device offload time = )([0-9.+-e]+)(?: \((?:s|ms|us)\))',
  'bitpermute':'(?:Average execution time of the kernel: )([0-9.+-e]+)(?: \(us\))',
  'black-scholes':'(?:Processing time on GPU: )([0-9.+-e]+)(?: \(ms\))',
  'blas-dot':'(?:Average cublasDotEx execution time )([0-9.+-e]+)(?: \(ms\))',
  'blas-fp8gemm':'(?:Average cublasLtMatmul execution time )([0-9.+-e]+)(?: \(us\))',
  'blas-gemm':'(?:Average GEMM execution time: )([0-9.+-e]+)(?: \(us\))',
  'blas-gemmBatched':'(?:average execution time: )([0-9.+-e]+)(?: us)',
  'blas-gemmEx':'([0-9.+-e]+)(?: TOP/s)',
  'blas-gemmEx2':'([0-9.+-e]+)(?: TOP/s)',
  'blas-gemmStridedBatched':'(?:average execution time: )([0-9.+-e]+)(?: us)',
  'blockAccess':'(?:Average execution time of the [A-Za-z]+ [A-Za-z]+: )([0-9.+-e]+)(?: \(us\))',
  'blockexchange':'(?:Average execution time of kernel: )([0-9.+-e]+)(?: \(us\))',
  'bm3d':'',
  'bmf':'(?:elapsed time \(GPUKERNELLOOP\): )([0-9.+-e]+)(?:s)',
  'bn':'(?:Average execution time of genScoreKernel: )([0-9.+-e]+)(?: \(s\))',
  'bonds':'(?:Average processing time on GPU: )([0-9.+-e]+)(?: \(ms\))',
  'boxfilter':'(?:Average kernel execution time )([0-9.+-e]+)(?: \(us\))',
  'bscan':'(?:Average execution time: )([0-9.+-e]+)(?: \(us\))',
  'bsearch':'(?:Average kernel execution time \(bs[1-9]\) )([0-9.+-e]+)(?: \(s\))',
  'bspline-vgh':'(?:Total kernel execution time )([0-9.+-e]+)(?: \(s\))',
  'bsw':'(?:Total loop iteration time \(seconds\):)([0-9.+-e]+)',
  'btree':'(?:Total device execution time = )([0-9.+-e]+)(?: s)',
  'burger':'(?:Total kernel execution time )([0-9.+-e]+)(?: \(s\))',
  'bwt':'(?:Device time: )([0-9.+-e]+)(?: (?:s|ms|us))',
  'car':'(?:Average kernel execution time )([0-9.+-e]+)(?: \(s\))',
  'cbsfil':'(?:Average kernel execution time )([0-9.+-e]+)(?: \(s\))',
  'cc':'(?:Average kernel execution time: )([0-9.+-e]+)(?: s)',
  'ccl':'',
  'ccs':'(?:Average kernel execution time )([0-9.+-e]+)(?: \(s\))',
  'ccsd-trpdrv':'(?:avg=)([0-9.+-e]+)',
  'ced':'(?:Total time )([0-9.+-e]+)(?: secs)',
  'cfd':'(?:Total execution time of kernels = )([0-9.+-e]+)(?:\(s\))',
  'chacha20':'(?:Average execution time of kernels: )([0-9.+-e]+)(?: \(us\))',
  'channelShuffle':'(?:Average time of channel shuffle \(\w+\): )([0-9.+-e]+)(?: \(ms\))',
  'channelSum':'(?:Average time of channel sum \(\w+\): )([0-9.+-e]+)(?: \(ms\))',
  'che':'(?:Kernel exeuction time on the GPU \([0-9]+ iterations\) = )([0-9.+-e]+)(?: \(s\))',
  'chemv':'(?:Average execution time of chemv kernels: )([0-9.+-e]+)(?: \(us\))',
  'chi2':'(?:Average kernel execution time = )([0-9.+-e]+)(?: \(s\))',
  'clenergy':'(?:Kernel time: )([0-9.+-e]+)(?: seconds)',
  'clink':'(?:Average kernel time: )([0-9.+-e]+)(?: ms)',
  'clock':'(?:Total clocks = )([0-9.+-e]+)',
  'cm':'',
  'cmembench':'(?:Average kernel execution time \(memory access width = [0-9]+ bytes\): )([0-9.+-e]+)(?: ms)',
  'cmp':'',
  'cobahh':'(?:Average kernel execution time )([0-9.+-e]+)(?: \(us\))',
  'collision':'(?:Average execution time of the function [A-Za-z_]+: )([0-9.+-e]+)(?: \(us\))',
  'colorwheel':'(?:Average kernel execution time : )([0-9.+-e]+)(?: \(ms\))',
  'columnarSolver':'',
  'complex':'(?:Average kernel execution time \([a-z]+\) )([0-9.+-e]+)(?: \(s\))',
  'compute-score':'(?:Kernel Time = )([0-9.+-e]+)(?: ms)',
  'concat':'(?:Average kernel execution time: )([0-9.+-e]+)(?: \(us\))',
  'concurrentKernels':'(?:Measured time for sample = )([0-9.+-e]+)(?:s)',
  'contract':'(?:Average kernel execution time )([0-9.+-e]+)(?: \(s\))',
  'conversion':'(?:average time\(sec\):)([0-9.+-e]+)(?:,)',
  'convolution1D':'(?:Average kernel execution time of conv1d[-\sA-Za-z]+ kernel: )([0-9.+-e]+)(?: \(us\))',
  'convolution3D':'Average kernel execution time of conv3d_[A-Za-z0-9]+ kernel: ([0-9.+-e]+)(?: \(us\))',
  'convolutionDeformable':'',
  'convolutionSeparable':'(?:Average kernel execution time )([0-9.+-e]+)(?: \(s\))',
  'cooling':'(?:Average kernel execution time )([0-9.+-e]+)(?: \((?:s|ms|us)\))',
  'coordinates':'(?:Average execution time of [A-Za-z]+ transform: )([0-9.+-e]+)(?: \(us\))',
  'copy':'(?:| Total time: )([0-9.+-e]+)(?: ms)',
  'crc64':'([0-9.+-e]+)(?: MB\/s)',
  'cross':'(?:Average execution time of cross[0-9]+ kernel: )([0-9.+-e]+)(?: \((?:s|ms|us)\))',
  'crossEntropy':'(?:Average GPU kernel time \(ms\) : )([0-9.+-e]+)',
  'crs':'(?:Total encoding time )([0-9.+-e]+)(?: \(s\))',
  'd2q9-bgk':'(?:average kernel execution time over [0-9]+ iterations:[\s]+)([0-9.+-e]+)(?: \(us\))',
  'd3q19-bgk':'',
  'damage':'(?:Average kernel execution time )([0-9.+-e]+)(?: \((?:s|ms|us)\))',
  'daphne':'(?:Elapsed time: )([0-9.+-e]+)(?: seconds)',
  'dct8x8':'(?:Average DCT8x8 kernel execution time )([0-9.+-e]+)(?: \(s\))',
  'ddbp':'(?:Total kernel execution )([0-9.+-e]+)(?: \(s\))',
  'debayer':'(?:Average kernel execution time )([0-9.+-e]+)(?: \(s\))',
  'degrid':'(?:Average kernel execution time )([0-9.+-e]+)(?: \(s\))',
  'dense-embedding':'(?:Average execution time of dense embedding kernel \(k2\): )([0-9.+-e]+)(?: \(us\))',
  'depixel':'(?:Average kernel time over [0-9]+ iterations: )([0-9.+-e]+)(?: \(s\))',
  'deredundancy':'(?:Device offload time )([0-9.+-e]+)(?: secs)',
  'determinant':'(?:Average execution time: )([0-9.+-e]+)(?: \(us\))',
  'diamond':'',
  'dispatch':'(?:mean = )([0-9.+-e]+)(?: us)',
  'distort':'(?:Average kernel execution time: )([0-9.+-e]+)(?: \(ms\))',
  'divergence':'(?:Total Time: )([0-9.+-e]+)',
  'doh':'Average kernel execution time : ([0-9.+-e]+)(?: \(us\))',
  'dp':'(?:Average [A-Za-z:_\s]+)([0-9.+-e]+)(?: \(s\))',
  'dpid':'(?:Average kernel execution time )([0-9.+-e]+)(?: \(s\))',
  'dropout':'(?:Total kernel execution time \(VEC[0-9]\) )([0-9.+-e]+)(?: \(s\))',
  'dslash':'(?:Total GFLOP/s = )([0-9.+-e]+)',
  'dwconv':'(?:Average execution time of dwconv2d_forward kernel: )([0-9.+-e]+)(?: \(ms\))',
  'dwconv1d':'',
  'dxtc1':'(?:Average kernel execution time )([0-9.+-e]+)(?: \(s\))',
  'dxtc2':'(?:Average kernel execution time )([0-9.+-e]+)(?: \(us\))',
  'easyWave':'(?:elapsed: )([0-9.+-e]+)(?: msec)',
  'ecdh':'(?:: )([0-9.+-e]+)(?: s)',
  'egs':'(?:Elapsed time [\s.]+)([0-9.+-e]+)(?: ms)',
  'eigenvalue':'(?:Average kernel execution time )([0-9.+-e]+)(?: \(us\))',
  'eikonal':'(?:Total Running Time: )([0-9.+-e]+)(?: \(sec\))',
  'entropy':'(?:execution time )([0-9.+-e]+)(?: \(s\))',
  'epistasis':'(?:Average kernel execution time: )([0-9.+-e]+)(?: \(s\))',
  'ert':'(?:runtime \([a-z1-9]*\): )([0-9.+-e]+)(?: \(s\))',
  'expdist':'(?:Average kernel execution time )([0-9.+-e]+)(?: \(s\))',
  'extend2':'(?:Average offload time )([0-9.+-e]+)(?: \(us\))',
  'extrema':'(?:Total kernel execution time: )([0-9.+-e]+)(?: \(s\))',
  'f16max':'(?:Average kernel execution time )([0-9.+-e]+)(?: \(us\))',
  'f16sp':'(?:Average kernel execution time )([0-9.+-e]+)(?: \(us\))',
  'face':'(?:Object detection time )([0-9.+-e]+)(?: \(s\))',
  'fdtd3d':'(?:Average kernel execution time )([0-9.+-e]+)(?: \((?:s|ms|us)\))',
  'feynman-kac':'(?:Average kernel time: )([0-9.+-e]+)(?: \((?:s|ms|us)\))',
  'fft':'(?:Average kernel execution time )([0-9.+-e]+)(?: \(s\))',
  'fhd':'(?:Device execution time )([0-9.+-e]+)(?: \(s\))',
  'filter':'(?:Average execution time of filter \(shared memory\) )([0-9.+-e]+)(?: \(ms\))',
  'flame':'(?:Total frame time is )([0-9.+-e]+)(?: us)',
  'flip':'(?:Average execution time of the flip kernel: )([0-9.+-e]+)(?: \(ms\))',
  'floydwarshall':'(?:Average kernel execution time )([0-9.+-e]+)(?: \(s\))',
  'floydwarshall2':'(?:Average kernel \([A-Za-z]+\) time:\s+)([0-9.+-e]+)(?: s)',
  'fluidSim':'(?:Average kernel execution time )([0-9.+-e]+)(?: \(s\))',
  'fpc':'(?:fpc2: average device offload time )([0-9.+-e]+)(?: \(s\))',
  'fpdc':'(?:Average compression kernel execution time )([0-9.+-e]+)(?: \(s\))',
  'frechet':'(?:Average kernel execution time )([0-9.+-e]+)(?: \(s\))',
  'fresnel':'(?:Average kernel execution time )([0-9.+-e]+)(?: \(s\))',
  'frna':'(?:Total kernel execution time )([0-9.+-e]+)(?: \(s\))',
  'fsm':'([0-9.+-e]+)(?:\s*#runtime \[s\])',
  'fwt':'(?:Average device execution time )([0-9.+-e]+)(?: \(s\))',
  'ga':'(?:Total kernel execution time )([0-9.+-e]+)(?: \(s\))',
  'gabor':'(?:Average kernel execution time: )([0-9.+-e]+)(?: \(us\))',
  'gamma-correction':'(?:Average kernel execution time )([0-9.+-e]+)(?: \(s\))',
  'gaussian':'(?:Device offloading time )([0-9.+-e]+)(?: \(us\))',
  'gc':'(?:average runtime \([0-9]+ runs\):\s+)([0-9.+-e]+)(?: s)',
  'gd':'(?:Training time takes )([0-9.+-e]+)(?: \(s\))',
  'ge-spmm':'(?:Average kernel \(method [0-9]\) execution time )([0-9.+-e]+)(?: \(us\))',
  'geam':'(?:matrix transpose time = )([0-9.+-e]+)(?: \(ms\))',
  'gels':'(?:Average kernel execution time : )([0-9.+-e]+)(?: \(us\))',
  'gelu':'(?:Average kernel execution time )([0-9.+-e]+)(?: \(ms\))',
  'gemv':'(?:Average kernel execution time: )([0-9.+-e]+)(?: \(us\))',
  'geodesic':'(?:Average kernel execution time )([0-9.+-e]+)(?: \(s\))',
  'gerbil':'(?:time \(real\) total \(1 \+ 2\) :\s+)([0-9.+-e]+)(?: s)',
  'gibbs':'(?:Average execution time of kernels: )([0-9.+-e]+)(?: \(us\))',
  'glu':'(?:Average execution time of GLU kernel \(split dimension = 2\): )([0-9.+-e]+)(?: \(us\))',
  'gmm':'(?:Execution time of the cluster function )([0-9.+-e]+)(?: \(s\))',
  'goulash':'(?:total kernel time )([0-9.+-e]+)(?:\(s\))',
  'gpp':'(?:Average kernel execution time )([0-9.+-e]+)(?: \(s\))',
  'graphB+':'(?:Total graphB\+ runtime:\s+)([0-9.+-e]+)(?: s)',
  'graphExecution':'(?:Execution time: )([0-9.+-e]+)(?: \(us\))',
  'grep':'',
  'grrt':'(?:Total kernel execution time \(task[0-9]+\) )([0-9.+-e]+)(?: \(s\))',
  'gru':'(?:Average execution time of gru_cell_forward: )([0-9.+-e]+)(?: \(us\))',
  'haccmk':'(?:Average kernel execution time )([0-9.+-e]+)(?: \(s\))',
  'halo-finder':'',
  'hausdorff':'(?:Average execution time of kernels: )([0-9.+-e]+)(?: \(ms\))',
  'haversine':'',
  'hbc':'',
  'heartwall':'',
  'heat':'',
  'heat2d':'',
  'hellinger':'',
  'henry':'',
  'hexciton':'',
  'histogram':'(?:Avg time )([0-9.+-e]+)(?: us )',
  'hmm':'(?:Device execution time of Viterbi iterations )([0-9.+-e]+)(?: \(s\))',
  'hogbom':'',
  'hotspot':'',
  'hotspot3D':'',
  'hpl':'',
  'hungarian':'',
  'hwt1d':'(?:Average device offload time )([0-9.+-e]+)(?: \(s\))',
  'hybridsort':'(?:GPU execution time: )([0-9.+-e]+)(?: ms)',
  'hypterm':'',
  'idivide':'',
  'interleave':'',
  'interval':'',
  'intrinsics-cast':'',
  'intrinsics-simd':'',
  'inversek2j':'(?:Average kernel execution time )([0-9.+-e]+)(?: \(us\))',
  'is':'',
  'ising':'(?:elapsed time: )([0-9.+-e]+)(?: sec)',
  'iso2dfd':'(?:Total kernel execution time )([0-9.+-e]+)(?: \(ms\))',
  'jaccard':'',
  'jacobi':'(?:Total elapsed time: )([0-9.+-e]+)(?: seconds)',
  'jenkins-hash':'(?:Average kernel execution time : )([0-9.+-e]+)(?: \(s\))',
  'kalman':'',
  'keccaktreehash':'',
  'keogh':'',
  'kernelLaunch':'',
  'kmc':'',
  'kmeans':'',
  'knn':'',
  'kurtosis':'',
  'lanczos':'',
  'langevin':'',
  'langford':'',
  'laplace':'(?:iterations: )([0-9.+-e]+)(?: s)',
  'laplace3d':'',
  'lavaMD':'(?:Device offloading time:\s)([0-9.+-e]+)(?: s)',
  'layernorm':'',
  'layout':'(?:Average kernel execution time \(SoA\): )([0-9.+-e]+)(?: \(us\))',
  'lci':'',
  'lda':'',
  'ldpc':'',
  'lebesgue':'',
  'leukocyte':'',
  'lfib4':'',
  'libor':'(?:Average kernel execution time : )([0-9.+-e]+)(?: \(s\))',
  'lid-driven-cavity':'',
  'lif':'(?:Average kernel execution time: )([0-9.+-e]+)(?: \(us\))',
  'linearprobing':'(?:Kernel execution time \(iterate\): )([0-9.+-e]+)(?: \(s\))',
  'log2':'',
  'logan':'',
  'logic-resim':'',
  'logic-rewrite':'',
  'logprob':'(?:Average execution time of kernels: )([0-9.+-e]+)(?: \(us\))',
  'lombscargle':'(?:Average kernel execution time )([0-9.+-e]+)(?: \(us\))',
  'loopback':'',
  'lr':'',
  'lrn':'',
  'lsqt':'',
  'lud':'',
  'ludb':'',
  'lulesh':'',
  'lzss':'',
  'mallocFree':'',
  'mandelbrot':'(?:Average kernel execution time: )([0-9.+-e]+)(?: ms)',
  'marchingCubes':'',
  'mask':'(?:Average execution time of \w+ kernel: )([0-9.+-e]+)(?: \(us\))',
  'match':'',
  'matern':'',
  'matrix-rotate':'(?:Average kernel execution time: )([0-9.+-e]+)(?: \(s\))',
  'matrixT':'',
  'maxFlops':'',
  'maxpool3d':'(?:Average kernel execution time: )([0-9.+-e]+)(?: \(s\))',
  'mcmd':'',
  'mcpr':'',
  'md':'(?:Average kernel execution time )([0-9.+-e]+)(?: \(s\))',
  'md5hash':'',
  'mdh':'',
  'meanshift':'(?:Average execution time of mean-shift \(opt\) )([0-9.+-e]+)(?: ms)',
  'medianfilter':'(?:Average kernel execution time: )([0-9.+-e]+)(?: \(s\))',
  'memcpy':'',
  'memtest':'',
  'merge':'(?:Average kernel execution time: )([0-9.+-e]+)(?: \(us\))',
  'merkle':'(?: )([0-9.+-e]+)(?: ms)',
  'metropolis':'(?:Total kernel time \(metropolis simulation\) )([0-9.+-e]+)(?: secs)',
  'mf-sgd':'',
  'michalewicz':'(?:Average execution time of kernel \(dim = [0-9]+\): )([0-9.+-e]+)(?: \(us\))',
  'miniDGS':'',
  'miniFE':'',
  'miniWeather':'',
  'minibude':'(?:Total kernel time:\s+)([0-9.+-e]+)(?: ms)',
  'minimap2':'(?:Total kernel execution time: )([0-9.+-e]+)(?: \(s\))',
  'minimod':'(?:Average kernel time per iteration: )([0-9.+-e]+)(?: s)',
  'minisweep':'(?:kernel time: )([0-9.+-e]+)(?: \(s\))',
  'minkowski':'(?:Average kernel execution time: )([0-9.+-e]+)(?: \(s\))',
  'minmax':'(?:Average execution time of thrust.*: )([0-9.+-e]+)(?: \(us\))',
  'mis':'(?:compute time: )([0-9.+-e]+)(?: s)',
  'mixbench':'(?:Total kernel execution time: )([0-9.+-e]+)(?: \(s\))',
  'mmcsf':'(?:Total GPU time: )([0-9.+-e]+)(?: sec)',
  'mnist':'(?:Total time \(learn \+ test\) )([0-9.+-e]+)(?: secs)',
  'morphology':'(?:Average kernel execution time \([A-Za-z]+\): )([0-9.+-e]+)(?: \(s\))',
  'mpc':'(?:compression time: )([0-9.+-e]+)(?: ms)',
  'mr':'(?:Total kernel execution time \(\w+\s*\): )([0-9.+-e]+)(?: \(ms\))',
  'mrc':'(?:Average execution time of MRC2* kernel: )([0-9.+-e]+)(?: \(us\))',
  'mrg32k3a':'(?:Average execution time on \w+: )([0-9.+-e]+)(?: \(us\))',
  'mriQ':'(?:compute\w+ time: )([0-9.+-e]+)(?: s)',
  'mt':'(?:Time = )([0-9.+-e]+)(?: s)',
  'mtf':'(?:Average execution time: )([0-9.+-e]+)(?: \(s\))',
  'multimaterial':'(?:Compact matrix, cell centric, alg [0-9]+: )([0-9.+-e]+)(?: msec)',
  'multinomial':'(?:Average execution time of sampleMultinomialOnce kernel: )([0-9.+-e]+)(?: \(us\))',
  'murmurhash3':'(?:Average kernel execution time )([0-9.+-e]+)(?: \(s\))',
  'myocyte':'(?:Total kernel execution time )([0-9.+-e]+)(?: \(s\))',
  'nbnxm':'(?:Average kernel execution time \(w/o shift\): )([0-9.+-e]+)(?: \(us\))',
  'nbody':'(?:Total Time \(s\)[ ]*: )([0-9.+-e]+)',
  'ne':'(?:Average kernel execution time: )([0-9.+-e]+)(?: \(s\))',
  'nlll':'(?:Average execution time of nll loss forward reduce 2D kernel: )([0-9.+-e]+)(?: \(us\))',
  'nms':'(?:Average kernel execution time \(.+\: )([0-9.+-e]+)(?: \(s\))',
  'nn':'(?:Average kernel execution time: )([0-9.+-e]+)(?: \(us\))',
  'nonzero':'(?:Average time for .+: )([0-9.+-e]+)(?: \(us\))',
  'norm2':'(?:execution time = )([0-9.+-e]+)(?: \(us\))',
  'nosync':'(?:Average execution time: )([0-9.+-e]+)(?: \(us\))',
  'nqueen':'(?:Average kernel execution time: )([0-9.+-e]+)(?: \(s\))',
  'ntt':'(?:Average kernel execution time: )([0-9.+-e]+)(?: \(us\))',
  'nw':'(?:Total kernel execution time: )([0-9.+-e]+)(?: \(s\))',
  'openmp':'(?:Work took )([0-9.+-e]+)(?: seconds)',
  'opticalFlow':'(?:Processing time on \w+: )([0-9.+-e]+)(?: \(ms\))',
  'overlap':'(?:Avg. time when overlapped using [0-9]+ streams.*: )([0-9.+-e]+)(?: ms)',
  'overlay':'',
  'p2p':'',
  'p4':'(?:Average execution time of postprocess kernel: )([0-9.+-e]+)(?: \(us\))',
  'pad':'(?:Total padding execution time for [0-9.+-e]+ iterations: )([0-9.+-e]+)(?: \((?:s|ms|us)\))',
  'page-rank':'(?:Total kernel execution time: )([0-9.+-e]+)(?: \(s\))',
  'particle-diffusion':'(?:Average kernel execution time: )([0-9.+-e]+)(?: \(s\))',
  'particlefilter':'(?:Device offloading time: )([0-9.+-e]+)(?: \(s\))',
  'particles':'(?:Total execution time of [0-9]+ loop iterations: )([0-9.+-e]+)(?: \(s\))',
  'pathfinder':'(?:Device offloading time = )([0-9.+-e]+)(?: \(s\))',
  'pcc':'([0-9.+-e]+)(?: \(s\))',
  'perlin':'',
  'permutate':'',
  'permute':'',
  'perplexity':'',
  'phmm':'',
  'pingpong':'',
  'pitch':'',
  'pnpoly':'',
  'pns':'(?:Total device execution time: )([0-9.+-e]+)(?: s)',
  'pointwise':'',
  'pool':'',
  'popcount':'',
  'prefetch':'',
  'present':'',
  'prna':'',
  'projectile':'',
  'pso':'',
  'qem':'',
  'qkv':'',
  'qrg':'',
  'qtclustering':'',
  'quicksort':'',
  'radixsort':'',
  'radixsort2':'',
  'rainflow':'',
  'randomAccess':'',
  'rayleighBenardConvection':'',
  'reaction':'',
  'recursiveGaussian':'',
  'relu':'',
  'remap':'',
  'resize':'',
  'resnet-kernels':'',
  'reverse':'',
  'reverse2D':'',
  'rfs':'',
  'ring':'',
  'rle':'',
  'rng-wallace':'',
  'rodrigues':'',
  'romberg':'',
  'rotary':'',
  'rowwiseMoments':'',
  'rsbench':'',
  'rsc':'(?:Total task execution time for [0-9.+-e]+ iterations: )([0-9.+-e]+)(?: \((?:s|ms|us)\))',
  'rsmt':'',
  'rtm8':'',
  'rushlarsen':'',
  's3d':'(?:Total time )([0-9.+-e]+)(?: secs)',
  's8n':'',
  'sa':'',
  'sad':'',
  'sampling':'',
  'saxpy-ompt':'',
  'sc':'(?:Total stream compaction time for [0-9.+-e]+ iterations: )([0-9.+-e]+)(?: \((?:s|ms|us)\))',
  'scan':'',
  'scan2':'',
  'scan3':'',
  'scel':'',
  'score':'',
  'sddmm-batch':'',
  'seam-carving':'',
  'secp256k1':'',
  'segment-reduce':'',
  'segsort':'',
  'sheath':'(?:Time per time step: )([0-9.+-e]+)(?: \(ms\))',
  'shmembench':'',
  'shuffle':'',
  'si':'',
  'simpleMultiDevice':'',
  'simpleSpmv':'',
  'simplemoc':'(?:Total kernel time:       )([0-9.+-e]+)(?: seconds)',
  'slit':'',
  'slu':'',
  'snake':'',
  'sobel':'',
  'sobol':'',
  'softmax':'',
  'softmax-fused':'',
  'softmax-online':'',
  'sort':'',
  'sortKV':'',
  'sosfil':'',
  'sparkler':'',
  'spaxpby':'',
  'spd2s':'',
  'spgeam':'',
  'spgemm':'',
  'sph':'',
  'split':'',
  'spm':'',
  'spmm':'',
  'spmv':'',
  'spnnz':'',
  'sps2d':'',
  'spsm':'',
  'spsort':'',
  'sptrsv':'',
  'srad':'',
  'ss':'',
  'ssim':'',
  'sss':'',
  'sssp':'',
  'stddev':'',
  'stencil1d':'',
  'stencil3d':'',
  'streamCreateCopyDestroy':'',
  'streamOrderedAllocation':'',
  'streamPriority':'',
  'streamUM':'',
  'streamcluster':'',
  'stsg':'',
  'su3':'(?:Total kernel execution time = )([0-9.+-e]+)(?: \(s\))',
  'surfel':'',
  'svd3x3':'',
  'sw4ck':'',
  'swish':'',
  'tensorAccessor':'',
  'tensorT':'',
  'testSNAP':'',
  'thomas':'',
  'threadfence':'',
  'tissue':'',
  'tonemapping':'',
  'tpacf':'',
  'tqs':'(?:Total task execution time for [0-9.+-e]+ iterations: )([0-9.+-e]+)(?: \((?:s|ms|us)\))',
  'triad':'',
  'tridiagonal':'(?:Time = )([0-9.+-e]+)(?: s)',
  'tsa':'',
  'tsne':'',
  'tsp':'',
  'unfold':'',
  'urng':'',
  'vanGenuchten':'(?:Average kernel execution time: )([0-9.+-e]+)(?: \(s\))',
  'vmc':'',
  'vol2col':'',
  'vote':'',
  'voxelization':'',
  'warpexchange':'',
  'warpsort':'',
  'wedford':'',
  'winograd':'',
  'wlcpow':'',
  'wmma':'',
  'word2vec':'',
  'wordcount':'',
  'wsm5':'',
  'wyllie':'',
  'xlqc':'',
  'xsbench':'',
  'zerocopy':'(?:Average kernel execution time: )([0-9.+-e]+)(?: ms)',
  'zeropoint':'(?:Average execution time of zero-point kernel: )([0-9.+-e]+)(?: \(us\))',
  'zmddft':'',
  'zoom':''
}

