regexps = {
  'accuracy':'(?:Average execution time of accuracy kernel: )([0-9.+-e]+)(?: \(us\))',
  'ace':'(?:Offload time: )([0-9.+-e]+)(?: \(ms\))',
  'adam':'(?:Average kernel execution time )([0-9.+-e]+)(?: \(ms\))',
  'addBiasResidualLayerNorm':'',
  'adv':'(?:elapsed time=)([0-9.+-e]+)(?: )',
  'aes':'',
  'affine':'',
  'aidw':'(?:Average execution time of AIDW_Kernel_Tiled )([0-9.+-e]+)(?: \(s\))',
  'aligned-types':'',
  'all-pairs-distance':'(?:Average kernel execution time \(w/o? shared memory\): )([0-9.+-e]+)(?: \(us\))',
  'allreduce':'',
  'amgmk':'',
  'ans':'',
  'aobench':'(?:Average render time: )([0-9.+-e]+)(?: sec)',
  'aop':'(?:elapsed time for each run *: )([0-9.+-e]+)(?:ms)',
  'asmooth':'(?:Average filtering time )([0-9.+-e]+)(?: \(s\))',
  'assert':'',
  'asta':'(?:Average kernel execution time )([0-9.+-e]+)(?: \(s\))',
  'atan2':'',
  'atomicAggregate':'(?:Total kernel time \(32 locations\): )([0-9.+-e]+)(?: \(s\))',
  'atomicCAS':'(?:Average execution time: )([0-9.+-e]+)(?: \(s\))',
  'atomicCost':'(?:Average execution time of WithoutAtomicOnGlobalMem: )([0-9.+-e]+)(?: \(us\))',
  'atomicIntrinsics':'',
  'atomicPerf':'',
  'atomicReduction':'(?:The average performance of reduction is )([0-9.+-e]+)(?: GBytes/sec)',
  'atomicSystemWide':'',
  'attention':'(?:Average execution time of kernels )([0-9.+-e]+)(?: \(ms\))',
  'attentionMultiHead':'',
  'axhelm':'',
  'b+tree':'',
  'babelstream':'',
  'background-subtract':'',
  'backprop':'(?:time = )([0-9.+-e]+)(?:\(s\))',
  'bezier-surface':'(?:kernel execution time: )([0-9.+-e]+)(?: ms)',
  'bfs':'',
  'bh':'(?:Total kernel execution time: )([0-9.+-e]+)(?: s)',
  'bicgstab':'',
  'bilateral':'(?:Average kernel execution time \([1-9]x[1-9]\) )([0-9.+-e]+)(?: \(ms\))',
  'bincount':'',
  'binomial':'(?:Total binomialOptionsGPU\(\) time: )([0-9.+-e]+)(?: msec)',
  'bitcracker':'',
  'bitonic-sort':'(?:Total kernel execution time: )([0-9.+-e]+)(?: \(ms\))',
  'bitpacking':'(?:Device offload time = )([0-9.+-e]+)(?: \((?:s|ms|us)\))',
  'bitpermute':'',
  'black-scholes':'(?:Processing time on GPU: )([0-9.+-e]+)(?: \(ms\))',
  'blas-dot':'',
  'blas-fp8gemm':'',
  'blas-gemm':'',
  'blas-gemmBatched':'',
  'blas-gemmEx':'',
  'blas-gemmEx2':'',
  'blas-gemmStridedBatched':'',
  'blockAccess':'',
  'blockexchange':'',
  'bm3d':'',
  'bmf':'',
  'bn':'(?:Average execution time of genScoreKernel: )([0-9.+-e]+)(?: \(s\))',
  'bonds':'(?:Average processing time on GPU: )([0-9.+-e]+)(?: \(ms\))',
  'boxfilter':'(?:Average kernel execution time )([0-9.+-e]+)(?: \(us\))',
  'bscan':'',
  'bsearch':'(?:Average kernel execution time \(bs[1-9]\) )([0-9.+-e]+)(?: \(s\))',
  'bspline-vgh':'(?:Total kernel execution time )([0-9.+-e]+)(?: \(s\))',
  'bsw':'',
  'btree':'',
  'burger':'(?:Total kernel execution time )([0-9.+-e]+)(?: \(s\))',
  'bwt':'(?:Device time: )([0-9.+-e]+)(?: (?:s|ms|us))',
  'car':'',
  'cbsfil':'(?:Average kernel execution time )([0-9.+-e]+)(?: \(s\))',
  'cc':'',
  'ccl':'',
  'ccs':'',
  'ccsd-trpdrv':'(?:avg=)([0-9.+-e]+)',
  'ced':'',
  'cfd':'',
  'chacha20':'',
  'channelShuffle':'(?:Average time of channel shuffle \(\w+\): )([0-9.+-e]+)(?: \(ms\))',
  'channelSum':'(?:Average time of channel sum \(\w+\): )([0-9.+-e]+)(?: \(ms\))',
  'che':'',
  'chemv':'(?:Average execution time of chemv kernels: )([0-9.+-e]+)(?: \(us\))',
  'chi2':'',
  'clenergy':'(?:Kernel time: )([0-9.+-e]+)(?: seconds)',
  'clink':'(?:Average kernel time: )([0-9.+-e]+)(?: ms)',
  'clock':'',
  'cm':'',
  'cmembench':'',
  'cmp':'',
  'cobahh':'(?:Average kernel execution time )([0-9.+-e]+)(?: \(us\))',
  'collision':'',
  'colorwheel':'',
  'columnarSolver':'',
  'complex':'(?:Average kernel execution time \([a-z]+\) )([0-9.+-e]+)(?: \(s\))',
  'compute-score':'(?:Kernel Time = )([0-9.+-e]+)(?: ms)',
  'concat':'(?:Average kernel execution time: )([0-9.+-e]+)(?: \(us\))',
  'concurrentKernels':'(?:Measured time for sample = )([0-9.+-e]+)(?:s)',
  'contract':'',
  'conversion':'',
  'convolution1D':'',
  'convolution3D':'',
  'convolutionDeformable':'',
  'convolutionSeparable':'(?:Average kernel execution time )([0-9.+-e]+)(?: \(s\))',
  'cooling':'(?:Average kernel execution time )([0-9.+-e]+)(?: \((?:s|ms|us)\))',
  'coordinates':'',
  'copy':'',
  'crc64':'',
  'cross':'(?:Average execution time of cross[0-9]+ kernel: )([0-9.+-e]+)(?: \((?:s|ms|us)\))',
  'crossEntropy':'(?:Average GPU kernel time \(ms\) : )([0-9.+-e]+)',
  'crs':'(?:Total encoding time )([0-9.+-e]+)(?: \(s\))',
  'd2q9-bgk':'',
  'd3q19-bgk':'',
  'damage':'',
  'daphne':'',
  'dct8x8':'(?:Average DCT8x8 kernel execution time )([0-9.+-e]+)(?: \(s\))',
  'ddbp':'',
  'debayer':'',
  'degrid':'(?:Average kernel execution time )([0-9.+-e]+)(?: \(s\))',
  'dense-embedding':'(?:Average execution time of dense embedding kernel \(k2\): )([0-9.+-e]+)(?: \(us\))',
  'depixel':'',
  'deredundancy':'',
  'determinant':'',
  'diamond':'',
  'dispatch':'',
  'distort':'',
  'divergence':'',
  'doh':'',
  'dp':'(?:Average kernel execution time )([0-9.+-e]+)(?: \(s\))',
  'dpid':'',
  'dropout':'',
  'dslash':'',
  'dwconv':'(?:Average execution time of dwconv2d_forward kernel: )([0-9.+-e]+)(?: \(ms\))',
  'dwconv1d':'',
  'dxtc1':'',
  'dxtc2':'(?:Average kernel execution time )([0-9.+-e]+)(?: \(us\))',
  'easyWave':'',
  'ecdh':'(?:: )([0-9.+-e]+)(?: s)',
  'egs':'',
  'eigenvalue':'(?:Average kernel execution time )([0-9.+-e]+)(?: \(us\))',
  'eikonal':'',
  'entropy':'(?:execution time )([0-9.+-e]+)(?: \(s\))',
  'epistasis':'(?:Average kernel execution time: )([0-9.+-e]+)(?: \(s\))',
  'ert':'(?:runtime \([a-z1-9]*\): )([0-9.+-e]+)(?: \(s\))',
  'expdist':'(?:Average kernel execution time )([0-9.+-e]+)(?: \(s\))',
  'extend2':'(?:Average offload time )([0-9.+-e]+)(?: \(us\))',
  'extrema':'',
  'f16max':'',
  'f16sp':'(?:Average kernel execution time )([0-9.+-e]+)(?: \(us\))',
  'face':'',
  'fdtd3d':'(?:Average kernel execution time )([0-9.+-e]+)(?: \((?:s|ms|us)\))',
  'feynman-kac':'',
  'fft':'(?:Average kernel execution time )([0-9.+-e]+)(?: \(s\))',
  'fhd':'',
  'filter':'(?:Average execution time of filter \(shared memory\) )([0-9.+-e]+)(?: \(ms\))',
  'flame':'',
  'flip':'(?:Average execution time of the flip kernel: )([0-9.+-e]+)(?: \(ms\))',
  'floydwarshall':'(?:Average kernel execution time )([0-9.+-e]+)(?: \(s\))',
  'floydwarshall2':'',
  'fluidSim':'',
  'fpc':'(?:fpc2: average device offload time )([0-9.+-e]+)(?: \(s\))',
  'fpdc':'',
  'frechet':'',
  'fresnel':'',
  'frna':'',
  'fsm':'([0-9.+-e]+)(?:\s*#runtime \[s\])',
  'fwt':'(?:Average device execution time )([0-9.+-e]+)(?: \(s\))',
  'ga':'',
  'gabor':'(?:Average kernel execution time: )([0-9.+-e]+)(?: \(us\))',
  'gamma-correction':'(?:Average kernel execution time )([0-9.+-e]+)(?: \(s\))',
  'gaussian':'(?:Device offloading time )([0-9.+-e]+)(?: \(us\))',
  'gc':'',
  'gd':'(?:Training time takes )([0-9.+-e]+)(?: \(s\))',
  'ge-spmm':'',
  'geam':'',
  'gels':'',
  'gelu':'(?:Average kernel execution time )([0-9.+-e]+)(?: \(ms\))',
  'gemv':'',
  'geodesic':'',
  'gerbil':'',
  'gibbs':'',
  'glu':'(?:Average execution time of GLU kernel \(split dimension = 2\): )([0-9.+-e]+)(?: \(us\))',
  'gmm':'',
  'goulash':'(?:total kernel time )([0-9.+-e]+)(?:\(s\))',
  'gpp':'(?:Average kernel execution time )([0-9.+-e]+)(?: \(s\))',
  'graphB+':'',
  'graphExecution':'',
  'grep':'',
  'grrt':'',
  'gru':'',
  'haccmk':'(?:Average kernel execution time )([0-9.+-e]+)(?: \(s\))',
  'halo-finder':'',
  'hausdorff':'(?:Average execution time of kernels: )([0-9.+-e]+)(?: \(ms\))',
  'haversine':'',
  'hbc':'',
  'heartwall':'',
  'heat':'',
  'heat2d':'',
  'hellinger':'',
  'henry':'',
  'hexciton':'',
  'histogram':'(?:Avg time )([0-9.+-e]+)(?: us )',
  'hmm':'(?:Device execution time of Viterbi iterations )([0-9.+-e]+)(?: \(s\))',
  'hogbom':'',
  'hotspot':'',
  'hotspot3D':'',
  'hpl':'',
  'hungarian':'',
  'hwt1d':'(?:Average device offload time )([0-9.+-e]+)(?: \(s\))',
  'hybridsort':'(?:GPU execution time: )([0-9.+-e]+)(?: ms)',
  'hypterm':'',
  'idivide':'',
  'interleave':'',
  'interval':'',
  'intrinsics-cast':'',
  'intrinsics-simd':'',
  'inversek2j':'(?:Average kernel execution time )([0-9.+-e]+)(?: \(us\))',
  'is':'',
  'ising':'(?:elapsed time: )([0-9.+-e]+)(?: sec)',
  'iso2dfd':'(?:Total kernel execution time )([0-9.+-e]+)(?: \(ms\))',
  'jaccard':'',
  'jacobi':'(?:Total elapsed time: )([0-9.+-e]+)(?: seconds)',
  'jenkins-hash':'(?:Average kernel execution time : )([0-9.+-e]+)(?: \(s\))',
  'kalman':'',
  'keccaktreehash':'',
  'keogh':'',
  'kernelLaunch':'',
  'kmc':'',
  'kmeans':'',
  'knn':'',
  'kurtosis':'',
  'lanczos':'',
  'langevin':'',
  'langford':'',
  'laplace':'(?:iterations: )([0-9.+-e]+)(?: s)',
  'laplace3d':'',
  'lavaMD':'(?:Device offloading time:\s)([0-9.+-e]+)(?: s)',
  'layernorm':'',
  'layout':'(?:Average kernel execution time \(SoA\): )([0-9.+-e]+)(?: \(us\))',
  'lci':'',
  'lda':'',
  'ldpc':'',
  'lebesgue':'',
  'leukocyte':'',
  'lfib4':'',
  'libor':'(?:Average kernel execution time : )([0-9.+-e]+)(?: \(s\))',
  'lid-driven-cavity':'',
  'lif':'(?:Average kernel execution time: )([0-9.+-e]+)(?: \(us\))',
  'linearprobing':'(?:Kernel execution time \(iterate\): )([0-9.+-e]+)(?: \(s\))',
  'log2':'',
  'logan':'',
  'logic-resim':'',
  'logic-rewrite':'',
  'logprob':'(?:Average execution time of kernels: )([0-9.+-e]+)(?: \(us\))',
  'lombscargle':'(?:Average kernel execution time )([0-9.+-e]+)(?: \(us\))',
  'loopback':'',
  'lr':'',
  'lrn':'',
  'lsqt':'',
  'lud':'',
  'ludb':'',
  'lulesh':'',
  'lzss':'',
  'mallocFree':'',
  'mandelbrot':'(?:Average kernel execution time: )([0-9.+-e]+)(?: ms)',
  'marchingCubes':'',
  'mask':'(?:Average execution time of \w+ kernel: )([0-9.+-e]+)(?: \(us\))',
  'match':'',
  'matern':'',
  'matrix-rotate':'(?:Average kernel execution time: )([0-9.+-e]+)(?: \(s\))',
  'matrixT':'',
  'maxFlops':'',
  'maxpool3d':'(?:Average kernel execution time: )([0-9.+-e]+)(?: \(s\))',
  'mcmd':'',
  'mcpr':'',
  'md':'(?:Average kernel execution time )([0-9.+-e]+)(?: \(s\))',
  'md5hash':'',
  'mdh':'',
  'meanshift':'(?:Average execution time of mean-shift \(opt\) )([0-9.+-e]+)(?: ms)',
  'medianfilter':'(?:Average kernel execution time: )([0-9.+-e]+)(?: \(s\))',
  'memcpy':'',
  'memtest':'',
  'merge':'(?:Average kernel execution time: )([0-9.+-e]+)(?: \(us\))',
  'merkle':'(?: )([0-9.+-e]+)(?: ms)',
  'metropolis':'',
  'mf-sgd':'',
  'michalewicz':'',
  'miniDGS':'',
  'miniFE':'',
  'miniWeather':'',
  'minibude':'',
  'minimap2':'',
  'minimod':'(?:Average kernel time per iteration: )([0-9.+-e]+)(?: s)',
  'minisweep':'(?:kernel time: )([0-9.+-e]+)(?: \(s\))',
  'minkowski':'(?:Average kernel execution time: )([0-9.+-e]+)(?: \(s\))',
  'minmax':'',
  'mis':'',
  'mixbench':'',
  'mmcsf':'',
  'mnist':'(?:Total time \(learn \+ test\) )([0-9.+-e]+)(?: secs)',
  'morphology':'',
  'mpc':'',
  'mr':'(?:Total kernel execution time \(\w+\s*\): )([0-9.+-e]+)(?: \(ms\))',
  'mrc':'',
  'mrg32k3a':'',
  'mriQ':'',
  'mt':'',
  'mtf':'',
  'multimaterial':'',
  'multinomial':'(?:Average execution time of sampleMultinomialOnce kernel: )([0-9.+-e]+)(?: \(us\))',
  'murmurhash3':'(?:Average kernel execution time )([0-9.+-e]+)(?: \(s\))',
  'myocyte':'',
  'nbnxm':'(?:Average kernel execution time \(w/o shift\): )([0-9.+-e]+)(?: \(us\))',
  'nbody':'(?:Total Time \(s\)[ ]*: )([0-9.+-e]+)',
  'ne':'',
  'nlll':'',
  'nms':'',
  'nn':'',
  'nonzero':'',
  'norm2':'',
  'nosync':'',
  'nqueen':'',
  'ntt':'',
  'nw':'',
  'openmp':'',
  'opticalFlow':'',
  'overlap':'(?:Avg. time when overlapped using [0-9]+ streams.*: )([0-9.+-e]+)(?: ms)',
  'overlay':'',
  'p2p':'',
  'p4':'',
  'pad':'(?:Total padding execution time for [0-9.+-e]+ iterations: )([0-9.+-e]+)(?: \((?:s|ms|us)\))',
  'page-rank':'(?:Total kernel execution time: )([0-9.+-e]+)(?: \(s\))',
  'particle-diffusion':'(?:Average kernel execution time: )([0-9.+-e]+)(?: \(s\))',
  'particlefilter':'(?:Device offloading time: )([0-9.+-e]+)(?: \(s\))',
  'particles':'',
  'pathfinder':'(?:Device offloading time = )([0-9.+-e]+)(?: \(s\))',
  'pcc':'',
  'perlin':'',
  'permutate':'',
  'permute':'',
  'perplexity':'',
  'phmm':'',
  'pingpong':'',
  'pitch':'',
  'pnpoly':'',
  'pns':'(?:Total device execution time: )([0-9.+-e]+)(?: s)',
  'pointwise':'',
  'pool':'',
  'popcount':'',
  'prefetch':'',
  'present':'',
  'prna':'',
  'projectile':'',
  'pso':'',
  'qem':'',
  'qkv':'',
  'qrg':'',
  'qtclustering':'',
  'quicksort':'',
  'radixsort':'',
  'radixsort2':'',
  'rainflow':'',
  'randomAccess':'',
  'rayleighBenardConvection':'',
  'reaction':'',
  'recursiveGaussian':'',
  'relu':'',
  'remap':'',
  'resize':'',
  'resnet-kernels':'',
  'reverse':'',
  'reverse2D':'',
  'rfs':'',
  'ring':'',
  'rle':'',
  'rng-wallace':'',
  'rodrigues':'',
  'romberg':'',
  'rotary':'',
  'rowwiseMoments':'',
  'rsbench':'',
  'rsc':'(?:Total task execution time for [0-9.+-e]+ iterations: )([0-9.+-e]+)(?: \((?:s|ms|us)\))',
  'rsmt':'',
  'rtm8':'',
  'rushlarsen':'',
  's3d':'(?:Total time )([0-9.+-e]+)(?: secs)',
  's8n':'',
  'sa':'',
  'sad':'',
  'sampling':'',
  'saxpy-ompt':'',
  'sc':'(?:Total stream compaction time for [0-9.+-e]+ iterations: )([0-9.+-e]+)(?: \((?:s|ms|us)\))',
  'scan':'',
  'scan2':'',
  'scan3':'',
  'scel':'',
  'score':'',
  'sddmm-batch':'',
  'seam-carving':'',
  'secp256k1':'',
  'segment-reduce':'',
  'segsort':'',
  'sheath':'(?:Time per time step: )([0-9.+-e]+)(?: \(ms\))',
  'shmembench':'',
  'shuffle':'',
  'si':'',
  'simpleMultiDevice':'',
  'simpleSpmv':'',
  'simplemoc':'(?:Total kernel time:       )([0-9.+-e]+)(?: seconds)',
  'slit':'',
  'slu':'',
  'snake':'',
  'sobel':'',
  'sobol':'',
  'softmax':'',
  'softmax-fused':'',
  'softmax-online':'',
  'sort':'',
  'sortKV':'',
  'sosfil':'',
  'sparkler':'',
  'spaxpby':'',
  'spd2s':'',
  'spgeam':'',
  'spgemm':'',
  'sph':'',
  'split':'',
  'spm':'',
  'spmm':'',
  'spmv':'',
  'spnnz':'',
  'sps2d':'',
  'spsm':'',
  'spsort':'',
  'sptrsv':'',
  'srad':'',
  'ss':'',
  'ssim':'',
  'sss':'',
  'sssp':'',
  'stddev':'',
  'stencil1d':'',
  'stencil3d':'',
  'streamCreateCopyDestroy':'',
  'streamOrderedAllocation':'',
  'streamPriority':'',
  'streamUM':'',
  'streamcluster':'',
  'stsg':'',
  'su3':'(?:Total kernel execution time = )([0-9.+-e]+)(?: \(s\))',
  'surfel':'',
  'svd3x3':'',
  'sw4ck':'',
  'swish':'',
  'tensorAccessor':'',
  'tensorT':'',
  'testSNAP':'',
  'thomas':'',
  'threadfence':'',
  'tissue':'',
  'tonemapping':'',
  'tpacf':'',
  'tqs':'(?:Total task execution time for [0-9.+-e]+ iterations: )([0-9.+-e]+)(?: \((?:s|ms|us)\))',
  'triad':'',
  'tridiagonal':'(?:Time = )([0-9.+-e]+)(?: s)',
  'tsa':'',
  'tsne':'',
  'tsp':'',
  'unfold':'',
  'urng':'',
  'vanGenuchten':'(?:Average kernel execution time: )([0-9.+-e]+)(?: \(s\))',
  'vmc':'',
  'vol2col':'',
  'vote':'',
  'voxelization':'',
  'warpexchange':'',
  'warpsort':'',
  'wedford':'',
  'winograd':'',
  'wlcpow':'',
  'wmma':'',
  'word2vec':'',
  'wordcount':'',
  'wsm5':'',
  'wyllie':'',
  'xlqc':'',
  'xsbench':'',
  'zerocopy':'(?:Average kernel execution time: )([0-9.+-e]+)(?: ms)',
  'zeropoint':'(?:Average execution time of zero-point kernel: )([0-9.+-e]+)(?: \(us\))',
  'zmddft':'',
  'zoom':''
}

