LAUNCHER = bash -c

program = main

$(program):
	cd src; make -f Makefile.NVD

clean:
	cd src; make -f Makefile.NVD clean

include ../include/miniFE-NVIDIA

run: $(program)
	$(LAUNCHER) "$(COMMAND)"

run_mem: $(program)
	nvidia-smi --query-gpu=memory.used,memory.total --format=csv --loop-ms=1 > log.mem &
	$(LAUNCHER) "$(COMMAND)"
	pkill nvidia-smi
	../scripts/m.sh
